//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnMonHoc_CNW.Models
{

    using DoAnMonHoc_CNW.Models;
    using System;
    using System.Collections.Generic;
    
    public partial class Khachhang
    {
        public Khachhang()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }

        public int MaKH { get; set; }
        public string HoTenK { get; set; }
        public Nullable<System.DateTime> NgaySinhK { get; set; }
        public string GioiTinhK { get; set; }
        public string SDTK { get; set; }
        public string TenTKK { get; set; }
        public string PassK { get; set; }
        public string EmailK { get; set; }
        public string DiaChiK { get; set; }
       
        public virtual ICollection<HoaDon> HoaDons{ get; set; }
    }
}
